-- Create courses table
create table if not exists courses (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  image text,
  instructor text,
  category text,
  progress integer default 0,
  total integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create modules table
create table if not exists modules (
  id bigint generated by default as identity primary key,
  course_id bigint references courses(id) on delete cascade,
  title text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create lessons table
create table if not exists lessons (
  id bigint generated by default as identity primary key,
  module_id bigint references modules(id) on delete cascade,
  title text not null,
  completed boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table courses enable row level security;
alter table modules enable row level security;
alter table lessons enable row level security;

-- Create policies (Open access for now to ensure functionality)
create policy "Public courses are viewable by everyone" on courses for select using (true);
create policy "Anyone can insert courses" on courses for insert with check (true);
create policy "Anyone can update courses" on courses for update using (true);

create policy "Public modules are viewable by everyone" on modules for select using (true);
create policy "Anyone can insert modules" on modules for insert with check (true);

create policy "Public lessons are viewable by everyone" on lessons for select using (true);
create policy "Anyone can insert lessons" on lessons for insert with check (true);

-- Create resources table
create table if not exists resources (
  id bigint generated by default as identity primary key,
  lesson_id bigint references lessons(id) on delete cascade,
  title text not null,
  type text not null, -- 'video', 'article', 'pdf', 'tool'
  url text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table resources enable row level security;

-- Create policies
create policy "Public resources are viewable by everyone" on resources for select using (true);
create policy "Anyone can insert resources" on resources for insert with check (true);
