-- SQL script to create the users table in Supabase
-- Run this in your Supabase SQL Editor (Dashboard > SQL Editor)

-- Create users table
CREATE TABLE IF NOT EXISTS users (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  username TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  account_type TEXT DEFAULT 'Student',
  subscription_plan TEXT DEFAULT 'Free',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create index on username for faster lookups
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);

-- Enable Row Level Security (RLS)
ALTER TABLE users ENABLE ROW LEVEL SECURITY;

-- Create policy to allow anonymous inserts (for registration)
CREATE POLICY "Allow anonymous registration" ON users
  FOR INSERT
  TO anon
  WITH CHECK (true);

-- Create policy to allow anonymous selects (for login - only for own data)
-- Note: This allows checking username/password, but you may want to restrict this further
CREATE POLICY "Allow anonymous login check" ON users
  FOR SELECT
  TO anon
  USING (true);

-- Create policy for authenticated users to read their own data
CREATE POLICY "Users can read own data" ON users
  FOR SELECT
  TO authenticated
  USING (auth.uid()::text = id::text);

-- Create policy for authenticated users to update their own data
CREATE POLICY "Users can update own data" ON users
  FOR UPDATE
  TO authenticated
  USING (auth.uid()::text = id::text);

-- Optional: Create a function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ language 'plpgsql';

-- Create trigger to automatically update updated_at
CREATE TRIGGER update_users_updated_at
  BEFORE UPDATE ON users
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Create user_courses table to store courses generated by users
CREATE TABLE IF NOT EXISTS user_courses (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  username TEXT NOT NULL,
  course_name TEXT NOT NULL,
  course_data JSONB NOT NULL,
  image TEXT DEFAULT '/placeholder.jpg',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes for faster lookups
CREATE INDEX IF NOT EXISTS idx_user_courses_username ON user_courses(username);
CREATE INDEX IF NOT EXISTS idx_user_courses_username_course ON user_courses(username, course_name);

-- Enable Row Level Security
ALTER TABLE user_courses ENABLE ROW LEVEL SECURITY;

-- Create policy to allow users to insert their own courses
CREATE POLICY "Users can insert own courses" ON user_courses
  FOR INSERT
  TO anon
  WITH CHECK (true);

-- Create policy to allow users to read their own courses
CREATE POLICY "Users can read own courses" ON user_courses
  FOR SELECT
  TO anon
  USING (true);

-- Create policy to allow users to update their own courses
CREATE POLICY "Users can update own courses" ON user_courses
  FOR UPDATE
  TO anon
  USING (true);

-- Create policy to allow users to delete their own courses
CREATE POLICY "Users can delete own courses" ON user_courses
  FOR DELETE
  TO anon
  USING (true);

-- Create trigger to update updated_at for user_courses
CREATE TRIGGER update_user_courses_updated_at
  BEFORE UPDATE ON user_courses
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

